import { describe, it, expect, beforeAll, afterAll, afterEach, vi } from 'vitest';
import mongoose from 'mongoose';
import { connectDatabase, disconnectDatabase } from '../config/database.js';
import { Job } from '../models/Job.model.js';
import { Resume } from '../models/Resume.model.js';
import { User } from '../models/User.model.js';
import * as jobController from '../controllers/job.controller.js';

// Mock JD parser service
vi.mock('../services/jd-parser.service.js', () => ({
  parseJD: vi.fn().mockResolvedValue({
    summary: 'A test job summary generated by mock parser',
    seniorityLevel: 'mid',
    focusWeights: { frontend: 30, backend: 50, devops: 20, ai: 0, mobile: 0 },
    requiredSkills: ['Node.js', 'React', 'MongoDB'],
    preferredSkills: ['TypeScript'],
    responsibilities: ['Build APIs', 'Optimize DB queries'],
    qualifications: ['B.S. in CS or equivalent'],
    niceToHaves: ['Docker experience'],
    tone: 'technical',
  }),
}));

process.env.NODE_ENV = 'test';
if (process.env.MONGODB_URI) {
  process.env.MONGODB_URI = process.env.MONGODB_URI.replace(/\/job_tailor.*$/, '/job_tailor_job_test');
} else {
  process.env.MONGODB_URI = 'mongodb://127.0.0.1:27017/job_tailor_job_test';
}

let testUserId: string;

beforeAll(async () => {
  await connectDatabase();
  const user = await User.create({
    email: 'job-test@example.com',
    passwordHash: '$2b$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345',
    firstName: 'Job',
    lastName: 'Tester',
  });
  testUserId = (user._id as mongoose.Types.ObjectId).toString();
});

afterAll(async () => {
  await Job.deleteMany({ userId: testUserId });
  await User.deleteMany({ _id: testUserId });
  await disconnectDatabase();
});

afterEach(async () => {
  await Job.deleteMany({ userId: testUserId });
});

describe('Job CRUD & Controller operations integration tests', () => {
  it('should successfully create a new job entry', async () => {
    const req = {
      user: { userId: testUserId },
      body: {
        companyName: 'Acme Corp',
        jobTitle: 'Software Engineer',
        location: 'Remote',
        workType: 'remote',
        employmentType: 'full-time',
        jdRawText: 'We are looking for a Node.js and React developer.',
      },
    } as any;

    let resData: any = null;
    const res = {
      status: (code: number) => {
        expect(code).toBe(201);
        return res;
      },
      json: (data: any) => {
        resData = data;
      },
    } as any;

    await jobController.createJob(req, res);

    expect(resData).not.toBeNull();
    expect(resData.success).toBe(true);
    expect(resData.data.job.companyName).toBe('Acme Corp');
    expect(resData.data.job.jobTitle).toBe('Software Engineer');
  });

  it('should read, update, list and delete job records successfully', async () => {
    // 1. Setup seed job
    const job = await Job.create({
      userId: testUserId,
      companyName: 'Alpha Inc',
      jobTitle: 'Frontend Lead',
      jdRawText: 'React expert needed.',
      status: 'saved',
    });
    const jobId = (job._id as mongoose.Types.ObjectId).toString();

    // 2. Read Job
    const readReq = { user: { userId: testUserId }, params: { id: jobId } } as any;
    let readData: any = null;
    const readRes = {
      json: (data: any) => { readData = data; },
    } as any;

    await jobController.getJob(readReq, readRes);
    expect(readData.success).toBe(true);
    expect(readData.data.job.companyName).toBe('Alpha Inc');

    // 3. Update Job status to applied
    const updateReq = {
      user: { userId: testUserId },
      params: { id: jobId },
      body: { status: 'applied' },
    } as any;
    let updateData: any = null;
    const updateRes = {
      json: (data: any) => { updateData = data; },
    } as any;

    await jobController.updateJob(updateReq, updateRes);
    expect(updateData.success).toBe(true);
    expect(updateData.data.job.status).toBe('applied');

    // 4. List Jobs
    const listReq = {
      user: { userId: testUserId },
      query: { page: '1', limit: '10' },
    } as any;
    let listData: any = null;
    const listRes = {
      json: (data: any) => { listData = data; },
    } as any;

    await jobController.listJobs(listReq, listRes);
    expect(listData.success).toBe(true);
    expect(listData.data.jobs).toHaveLength(1);
    expect(listData.data.jobs[0]._id.toString()).toBe(jobId);

    // 5. Delete Job
    const deleteReq = { user: { userId: testUserId }, params: { id: jobId } } as any;
    let deleteData: any = null;
    const deleteRes = {
      json: (data: any) => { deleteData = data; },
    } as any;

    await jobController.deleteJob(deleteReq, deleteRes);
    expect(deleteData.success).toBe(true);

    // Confirm job is gone from DB
    const checkDb = await Job.findById(jobId).lean();
    expect(checkDb).toBeNull();
  });

  it('should successfully trigger JD parser and attach details onto job record', async () => {
    const job = await Job.create({
      userId: testUserId,
      companyName: 'Beta Systems',
      jobTitle: 'DevOps Engineer',
      jdRawText: 'Kubernetes, AWS, Terraform raw requirements text.',
      status: 'saved',
    });
    const jobId = (job._id as mongoose.Types.ObjectId).toString();

    const parseReq = { user: { userId: testUserId }, params: { id: jobId } } as any;
    let parseData: any = null;
    const parseRes = {
      json: (data: any) => { parseData = data; },
    } as any;

    await jobController.parseJobJD(parseReq, parseRes);
    expect(parseData.success).toBe(true);
    expect(parseData.data.parsedJD.summary).toBe('A test job summary generated by mock parser');

    const updatedJob = await Job.findById(jobId).lean();
    expect(updatedJob!.parsedJD).not.toBeNull();
    expect(updatedJob!.parsedJD!.requiredSkills).toContain('Node.js');
  });

  it('should successfully attach a resume to a job', async () => {
    const job = await Job.create({
      userId: testUserId,
      companyName: 'Gamma Corp',
      jobTitle: 'Node Developer',
      jdRawText: 'Backend coding requirements.',
      status: 'saved',
    });
    const jobId = (job._id as mongoose.Types.ObjectId).toString();

    const resume = await Resume.create({
      userId: testUserId,
      version: 1,
      versionLabel: 'v1',
      filename: 'my_resume.pdf',
      rawText: 'Experienced Node developer skills here.',
      parsedContent: {
        summary: 'Expert dev summary',
        skills: [{ name: 'Node.js', category: 'backend', yearsOfExperience: 5, proficiency: 'expert', isHighlighted: true }],
        experience: [],
        projects: [],
        education: [],
        certifications: [],
        links: {},
      },
    });
    const resumeId = (resume._id as mongoose.Types.ObjectId).toString();

    const attachReq = {
      user: { userId: testUserId },
      params: { id: jobId },
      body: { resumeId },
    } as any;
    let attachData: any = null;
    const attachRes = {
      json: (data: any) => { attachData = data; },
    } as any;

    await jobController.attachResumeToJob(attachReq, attachRes);
    expect(attachData.success).toBe(true);
    expect(attachData.data.job.attachedResumeId.toString()).toBe(resumeId);

    // Clean up resume
    await Resume.deleteOne({ _id: resumeId });
  });
});
