import {
  describe,
  it,
  expect,
  beforeAll,
  afterAll,
  afterEach,
  vi,
} from "vitest";
import mongoose from "mongoose";
import { Resume } from "../models/Resume.model.js";
import { Job } from "../models/Job.model.js";
import { Profile } from "../models/Profile.model.js";
import { User } from "../models/User.model.js";
import * as resumeController from "../controllers/resume.controller.js";
import { connectTestDb, disconnectTestDb } from "./helpers/test-db.js";

// Mock tailor and scoring service dependencies
vi.mock("../services/resume-tailor.service.js", () => ({
  tailorResume: vi.fn().mockResolvedValue({
    tailoredSummary: "This is a mocked tailored summary generated by AI.",
    skills: [
      {
        name: "Node.js",
        category: "backend",
        yearsOfExperience: 5,
        proficiency: "expert",
        isHighlighted: true,
      },
    ],
    experience: [],
    projects: [],
    sectionOrder: ["summary", "skills", "experience", "projects", "education"],
    atsScore: {
      overallScore: 88,
      keywordMatchScore: 90,
      semanticMatchScore: 85,
      sectionCompletenessScore: 95,
      formatScore: 90,
      breakdown: {
        matchedSkills: [],
        missingSkills: [],
        weakSkills: [],
        actionItems: ["Enhance quantitative points"],
      },
    },
  }),
}));

vi.mock("../services/ats-scoring.service.js", () => ({
  scoreATS: vi.fn().mockResolvedValue({
    overallScore: 85,
    keywordMatchScore: 80,
    semanticMatchScore: 90,
    sectionCompletenessScore: 80,
    formatScore: 85,
    breakdown: {
      matchedSkills: [],
      missingSkills: [],
      weakSkills: [],
      actionItems: ["Verify certifications link format"],
    },
  }),
}));

process.env.NODE_ENV = "test";

let testUserId: string;
let testJobId: string;

beforeAll(async () => {
  await connectTestDb();

  // Setup user
  const user = await User.create({
    email: "resume-test@example.com",
    passwordHash:
      "$2b$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ012345",
    firstName: "Resume",
    lastName: "Tester",
  });
  testUserId = (user._id as mongoose.Types.ObjectId).toString();

  // Setup profile
  await Profile.create({
    userId: user._id,
    summary: "Initial summary",
    skills: [
      {
        name: "Node.js",
        category: "backend",
        yearsOfExperience: 5,
        proficiency: "expert",
        isHighlighted: true,
      },
    ],
    experience: [],
    projects: [],
    education: [],
    certifications: [],
    links: {},
  });

  // Setup job with parsed JD
  const job = await Job.create({
    userId: user._id,
    companyName: "Resume Corp",
    jobTitle: "Senior Dev",
    jdRawText: "Expert Node developer.",
    status: "saved",
    parsedJD: {
      summary: "Parsed summary description.",
      seniorityLevel: "senior",
      focusWeights: { frontend: 10, backend: 80, devops: 10, ai: 0, mobile: 0 },
      requiredSkills: ["Node.js"],
      preferredSkills: [],
      responsibilities: ["Build stuff"],
      qualifications: ["B.S."],
      niceToHaves: [],
      tone: "technical",
    },
  });
  testJobId = (job._id as mongoose.Types.ObjectId).toString();
});

afterAll(async () => {
  await Resume.deleteMany({ userId: testUserId });
  await Job.deleteMany({ userId: testUserId });
  await Profile.deleteMany({ userId: testUserId });
  await User.deleteMany({ _id: testUserId });
  await disconnectTestDb();
});

afterEach(async () => {
  await Resume.deleteMany({ userId: testUserId });
});

describe("Resume generation and tailoring controller integration tests", () => {
  it("should successfully generate a tailored resume for a parsed job", async () => {
    const req = {
      user: { userId: testUserId },
      body: { jobId: testJobId },
    } as any;

    let resData: any = null;
    const res = {
      status: (code: number) => {
        expect(code).toBe(201);
        return res;
      },
      json: (data: any) => {
        resData = data;
      },
    } as any;

    await resumeController.generateResume(req, res);

    expect(resData).not.toBeNull();
    expect(resData.success).toBe(true);
    expect(resData.data.resume.tailoredSummary).toBe(
      "This is a mocked tailored summary generated by AI.",
    );
    expect(resData.data.resume.atsScore.overallScore).toBe(88);
  });

  it("should read, update, list, and check quick ATS matches successfully", async () => {
    // 1. Create seed resume
    const resume = await Resume.create({
      userId: testUserId,
      jobId: testJobId,
      version: 1,
      versionLabel: "v1_seed",
      tailoredSummary: "Original tailored summary",
      skills: [
        {
          name: "Node.js",
          category: "backend",
          yearsOfExperience: 5,
          proficiency: "expert",
          isHighlighted: true,
        },
      ],
      experience: [],
      projects: [],
      sectionOrder: ["summary", "skills"],
      atsScore: {
        overallScore: 80,
        keywordMatchScore: 80,
        semanticMatchScore: 80,
        sectionCompletenessScore: 80,
        formatScore: 80,
        breakdown: {
          matchedSkills: [],
          missingSkills: [],
          weakSkills: [],
          actionItems: [],
        },
      },
      isProfileResume: true,
      status: "draft",
    });
    const resumeId = (resume._id as mongoose.Types.ObjectId).toString();

    // 2. Read single resume details
    const getReq = {
      user: { userId: testUserId },
      params: { id: resumeId },
    } as any;
    let getData: any = null;
    const getRes = {
      status: (code: number) => getRes,
      json: (data: any) => {
        getData = data;
      },
    } as any;

    await resumeController.getResume(getReq, getRes);
    expect(getData.success).toBe(true);
    expect(getData.data.resume.versionLabel).toBe("v1_seed");

    // 3. Update resume
    const updateReq = {
      user: { userId: testUserId },
      params: { id: resumeId },
      body: { tailoredSummary: "Manually updated summary content" },
    } as any;
    let updateData: any = null;
    const updateRes = {
      status: (code: number) => updateRes,
      json: (data: any) => {
        updateData = data;
      },
    } as any;

    await resumeController.updateResume(updateReq, updateRes);
    expect(updateData.success).toBe(true);
    expect(updateData.data.resume.tailoredSummary).toBe(
      "Manually updated summary content",
    );

    // 4. List resumes
    const listReq = {
      user: { userId: testUserId },
      query: { jobId: testJobId },
    } as any;
    let listData: any = null;
    const listRes = {
      status: (code: number) => listRes,
      json: (data: any) => {
        listData = data;
      },
    } as any;

    await resumeController.listResumes(listReq, listRes);
    expect(listData.success).toBe(true);
    expect(listData.data.resumes).toHaveLength(1);
    expect(listData.data.resumes[0]._id.toString()).toBe(resumeId);

    // 5. Quick ATS check
    const atsReq = {
      user: { userId: testUserId },
      body: { jobId: testJobId },
    } as any;
    let atsData: any = null;
    const atsRes = {
      status: (code: number) => atsRes,
      json: (data: any) => {
        atsData = data;
      },
    } as any;

    await resumeController.quickATSCheck(atsReq, atsRes);
    expect(atsData.success).toBe(true);
    expect(atsData.data.atsScore.overallScore).toBe(85);
  });
});
